### ISSUE TITLE
Specular Color 255;255;255 doesn't work initially

### ISSUE THREAD

**Issue by lucasw** [mogumbo/rviz_lighting#4]
When the specular color of a light is set to 255, 255, 255 the specular light doesn't work unless it is first changed and then can be restored to that value.

254,254,254 works fine, and a small sample of other values.

This is using a dae file exported from Blender, I don't think other Marker objects have much/any specular.

![specular](https://user-images.githubusercontent.com/1334122/45698240-6b641680-bb1c-11e8-826d-4cd7dd3995ab.png)

I remeshed the cube in blender to get a cheap not-quite-per-pixel effect.
[cube.zip](https://github.com/mogumbo/rviz_lighting/files/2393353/cube.zip)

```
rostopic pub /marker visualization_msgs/Marker "header:
  stamp: {secs: 0, nsecs: 0}
  frame_id: 'map'
ns: 'test'
id: 0
type: 10
action: 0
pose:
  orientation: {x: 0.0, y: 0.0, z: 0.0, w: 1.0}
scale: {x: 1.0, y: 1.0, z: 1.0}
mesh_resource: 'file://`pwd`/cube.dae'
mesh_use_embedded_materials: true" 
```
